### ISSUE TITLE
If downstream pipeline is in another project it fails 

### ISSUE THREAD

**Issue by sakarikl** [heikkipora/gitlab-radiator#117]
if downstream pipeline is in another project fails to start completely with error message: 

![image](https://github.com/heikkipora/gitlab-radiator/assets/439008/812c6440-1e6f-4146-9d0d-fe4f33f9f4ca)

Fix for it: https://github.com/heikkipora/gitlab-radiator/pull/115

**Comment by heikkipora** [comment]
Another repro leads to

<img width="1512" alt="image" src="https://github.com/heikkipora/gitlab-radiator/assets/259924/be1422f8-b56e-48b4-a478-73eb969b2099">

**Comment by heikkipora** [comment]
Fixed in https://github.com/heikkipora/gitlab-radiator/releases/tag/v4.2.0
