### ISSUE TITLE
Support gitlab project pagination for larger gitlabs

### ISSUE THREAD

**Issue by dwyerk** [heikkipora/gitlab-radiator#15]
If you have a gitlab with > 100 projects, only the first 100 that are returned by the API are visible in the radiator. Use the `page` parameter and iterate through the project pages until you receive an empty list in order to support all of the projects in a large gitlab.

**Comment by heikkipora** [comment]
I would be more than happy to get that as a pull request, if anybody has time for doing this shortly :). Otherwise I'll do it at some point during the coming weeks.

**Comment by dwyerk** [comment]
Totally fair. I did look into the code and found where you make the call to gitlab's `projects/` endpoint - but I'm not sure how to change the Bacon code to make additional requests. In an iterative world, it'd be something like:
```
result = ""
page = 1
while result != "[]":
    result = request("https://gitlab/api/v3/projects?page_size=100&page=" + page)
    page += 1
```
Bacon has a `repeat` that seems close but I'm new to this framework so it isn't clear what to do exactly. If you have a pointer to an example then I might be able to get something to work here.

**Comment by heikkipora** [comment]
A new major release is just out that includes the feature you suggested. See https://github.com/heikkipora/gitlab-radiator/releases/tag/2.0.3
Available on www.npmjs.com already.

I'm terribly sorry for the longish "coming weeks" I promised earlier ;-)

**Comment by dwyerk** [comment]
Haha no worries. Thanks for the heads up - I'll give it a try.
