### ISSUE TITLE
Always show last master pipeline build

### ISSUE THREAD

**Issue by leflamm** [heikkipora/gitlab-radiator#19]
Hi,

on one hand I like the idea that the last pipeline run of any branch of a project is shown - makes it easier to grasp what's going on.

On the other hand those last pipeline build statuses often hide failing master branches which usually is a big deal.

Can the radiator - in addition to the overall latest pipeline run - also show the last master branch pipeline? That would be awesome!

Thx for your work.
Cheers, Christian!

**Comment by leflamm** [comment]
An alternative would be to specify (regex?) which branches to care for. One could then have a standard radiator and an additional "master"-radiator alongside on the build monitor.

**Comment by heikkipora** [comment]
Sounds like a valid use case! Definitely goes on the TODO list

**Comment by heikkipora** [comment]
A new major release is just out that includes the feature you suggested. See https://github.com/heikkipora/gitlab-radiator/releases/tag/2.0.3
Available on www.npmjs.com already.
