### ISSUE TITLE
"Half of all projects" are not displayed

### ISSUE THREAD

**Issue by leflamm** [heikkipora/gitlab-radiator#24]
Hi,
I eagerly installed your new versions `2.0.3` and `2.1.0` because of the many new cool features. Unfortunately roughly half of our projects aren't displayed anymore.

I don't know in which way those are special compared to those that are still displayed.

Is there any extended debugging I could enable to track this down?

Cheers + Thx, Christian

**Comment by leflamm** [comment]
~~Really just a shot in the dark: those projects missing have pipelines with more than four stages. Those still displayed have four or less.~~
Nope, that's not it.

**Comment by leflamm** [comment]
They re-appear once the pipeline is triggered again. Interestingly for the other half of our projects this wasn't necessary. They were on the board instantly.

**Comment by heikkipora** [comment]
That is quite unexpected. Were the last pipelines in those projects really old or something?

I assume that (for some reason) the GitLab REST API responses didn't include those pipelines / jobs for some unknown reason.

**Comment by leflamm** [comment]
No, actually those projects that did appear were the really old ones (last-pipeline-run-wise).

**Comment by heikkipora** [comment]
gitlab-radiator includes projects based on these rules:
- membership = true in GitLab API call - "Limit by projects that the current user is a member of"
- regex matching (against optional regexes defined in the gitlab-radiator config file)
- project has at least one pipeline with at least one job

But I don't think any of those would explain why some of the builds appear only after running them again.

If you still encounter this problem and want to help investigate it, you could clone this repository and run it from source locally. A recent node installation and ```npm install && npm start```will start it locally. Just make sure it has access to the configuration file in the user's home directory (same as the production built one)

Placing a ```console.log(JSON.stringify(projects, null, 2))``` after ```const projects = await fetchProjectsPaged(config)``` in ```src/gitlab/projects.js``` will tell you if gitlab-radiator sees all the projects it should.

Similarly logging pipelines in ```src/gitlab/pipelines.js``` after ```const pipelines = await fetchLatestAndMasterPipeline(projectId, config)``` will tell if pipelines are received and parsed properly.

**Comment by leflamm** [comment]
Just FYI, if I restart `gitlab-radiator` then I can easily reproduce the situation that half of the projects are gone. I'll try to find the time to go through your suggested steps.

**Comment by leflamm** [comment]
I think I got it: the missing ones have a master branch pipeline status of "skipped". Those projects (repos) frequently receive commits whose subjects contain `[ci skip]`. Those commits will not start a pipeline run (that's default behavior). [1]

Those are missing on start. Once they had one proper pipeline run that's no longer an issue - even if they receive further `[ci skip]` commits after that run.

[1] Actually technically that's not correct. At least it will record a new pipeline run and mark it as "skipped".

**Comment by leflamm** [comment]
Problem here seems to be located on the Gitlab side then (see [1] in post before)

As somebody who is interested in a pipeline state I actually don't care if there was a commit that didn't trigger the pipeline. I don't even want to know about these. I care for the last one that _did_ trigger the pipeline.

**Comment by leflamm** [comment]
Can confirm it now. This even happens while the radiator runs:
- push a commit with subject containing `[ci skip]` -> pipeline is removed from radiator
- push another commit with subject _not_ containing `[ci skip]` -> pipeline reappears

**Comment by leflamm** [comment]
Early exit
```js
  if (gitlabJobs.length === 0) {
    return {}
  }
```
in `src/gitlab/pipelines.js` function "fetchJobs" rules those pipelines out. If I comment it back in all the pipelines are back - of course with missing information then
![image](https://user-images.githubusercontent.com/3337944/35875034-69dcc284-0b6e-11e8-8c23-b9e29cf91e7c.png)

**Comment by heikkipora** [comment]
I wasn't aware of the ``` [ci skip]``` commit flag feature at all. What you found is totally correct - and fixable by fetching more than the last pipeline.  At this point it also seems that a good default behavior for ```gitlab-radiator``` would be to show the last non-skipped pipeline status of course.

Let me spend some time later today on this and expect a new release then :)

**Comment by heikkipora** [comment]
@leflamm as I'm watching the SpaceX Falcon Heavy launch countdown I put out a new release (v2.1.1) - please give it a spin when you have time!

**Comment by leflamm** [comment]
Looking gooooood!

**Comment by heikkipora** [comment]
:fistbump: :pow!:
