### ISSUE TITLE
Jobs should maintain the same ordering as on gitlab

### ISSUE THREAD

**Issue by JamesMura** [heikkipora/gitlab-radiator#26]
Thank you for building the awesome radiator, we have noticed that the jobs from a pipeline is not consistent and sometimes is the reverse of what is in gitlab. I think it would be easier for users to understand if the jobs maintained the same exact order as on gitlab

**Comment by heikkipora** [comment]
I completely agree with you and at the same time wonder how I missed that myself!
GitLab seems to sort them alphabetically and my radiator just displayed them in API ID order. 
Sorted them by name instead :)

v2.1.4 (https://github.com/heikkipora/gitlab-radiator/releases/tag/2.1.4) should do the trick, please give it a spin!
