### ISSUE TITLE
Ignore archived Projects

### ISSUE THREAD

**Issue by leflamm** [heikkipora/gitlab-radiator#32]
Hi @heikkipora,

it would help our very crowded build monitor a whole lot if we could easily ignore/exclude archived projects. Either by default or enabled by a switch. These projects are set to be "read-only" and, hence, no active development can happen with them. IMHO, no need to display them on build monitor.

Would that be hard to do?

Cheers, Christian

**Comment by leflamm** [comment]
Here's a tiny PR: https://github.com/heikkipora/gitlab-radiator/pull/33

**Comment by heikkipora** [comment]
Looks like a good improvement (and PR) to me, thank you!

I did a small change: default value for `ignoreArchived` is now `true` which sounds like a more sensible default to me.
