### ISSUE TITLE
Configurations not being applied 

### ISSUE THREAD

**Issue by famlima** [heikkipora/gitlab-radiator#46]
Hello,

I've started to use this project yesterday. 
By now, i'm able to run it and see some radiators about every project in my internal gitlab. But what I want is to only see a certain project, so i've applied some configs that are in documentation, such as "exclude: ".  The problem is that is not applying those configs when I run it. 

My .yml file: 

`gitlabs:
  -
    access-token: xpto
    url: https://gitlab.mycompany.com
    projects:
      exclude: ^((?!someword).)*$
      excludePipelineStatus: ['canceled', 'pending']
      maxNonFailedJobsVisible: 3
projectsOrder: ['status', 'name']
zoom: 0.85
columns: 4`

Any ideia?

Regads,
Fernando Lima

**Comment by sakarikl** [comment]
Same issue here. can't get exclude or include to work

Also auth works if it is in root level not inside gitlabs as README says

**Comment by sakarikl** [comment]
maxNonFailedJobsVisible Should also be at the same level as projects. Not a child element of it.

**Comment by sakarikl** [comment]
I made a pull request to fix include and exclude issue
https://github.com/heikkipora/gitlab-radiator/pull/47

**Comment by famlima** [comment]
@sakarikl I'm trying to compile/run the code in my machine, but I'm having the following error:

(function (exports, require, module, __filename, __dirname) { import {basicAuth} from './auth'
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

Were you able to run it in your machine without problems?

Regards,
famlima

**Comment by wagner-ch** [comment]
Your fix #47 has been merged. Maybe you can close this issue and create seperate issues for any of the other topics so that they can be addressed seperately?

**Comment by wagner-ch** [comment]
I made a PR #50 to fix the other issues from this one. I think it's safe to close this issue now.

**Comment by heikkipora** [comment]
These fixes will be in the next release later today in case you install gitlab-radiator with npm
