### ISSUE TITLE
filter project by branches 

### ISSUE THREAD

**Issue by famlima** [heikkipora/gitlab-radiator#48]
Hello,

Another thing i'm trying to do and that I believe it would be very helpful, is to filter the project I want to monitor by branch, even monitor every branch I want per project.
Do you think is possible to add this?

Regards
Fernando Lima

**Comment by heikkipora** [comment]
I'm not personally in need of this kind of functionality, so it's not very likely to get implemented.
If you'd like to do it (or get someone to do it), please feel free to submit a PR.
