### ISSUE TITLE
Ability to use include and exclude project configurations

### ISSUE THREAD

**Issue by roshan092** [heikkipora/gitlab-radiator#52]
Unable to use the include and exclude together.
As per the current design we can either use include or exclude.
For the given projects [pro, pro-other, something] and for the configuration
`
  projects:
      include: .*/pro.*
      exclude: pro-other`

expected output projects on dashboard: [pro]
actual output projects on dashboard: [pro, pro-other]

**Comment by heikkipora** [comment]
The related PR has been merged and will be included in the next release.
