### ISSUE TITLE
Wrong logic of excludePipelineStatus

### ISSUE THREAD

**Issue by ghost** [heikkipora/gitlab-radiator#54]
Instead of excluding projects/pipelines with statuses listed in `excludePipelineStatus`, projects/pipelines with statuses **not** listed in `excludePipelineStatus` are excluded.

Moreover, the filtering is done on the project status (i.e. the status of the newest pipeline on master) instead of on the status of individual pipelines. This means that a failing pipeline on a branch is not shown if master is green.

**Comment by heikkipora** [comment]
Oh, that seems to be indeed true! Clearly a spot that doesn't have an automated test :)

**Comment by heikkipora** [comment]
The related PR has been merged and will be included in the next release.
