### ISSUE TITLE
Error when trying to fetch pipelines of projects without enabled pipelines feature

### ISSUE THREAD

**Issue by ghost** [heikkipora/gitlab-radiator#64]
After updating to GitLab 12.5.4, gitlab-radiator stopped working with error message

> Failed to communicate with GitLab API: Request failed with status code 403

It turned out that GitLab responds with status code 403 if one tries to fetch pipelines (`/api/v4/projects/<project_id>/pipelines`) of projects for which the pipelines (aka CI/CD) feature is not enabled.

**Comment by heikkipora** [comment]
Fix included in release v3.1.6
