### ISSUE TITLE
tags not filtering

### ISSUE THREAD

**Issue by someclouddude** [heikkipora/gitlab-radiator#73]
I have added tags to several repos but `?tags=` is not returning any results.
Running docker with node:alpine as non-root user with v3.2.0.

`git pull` && `git tag` shows the tags are present and confirmed on master in console.

We have many projects and would like to be able to sort not only with include for the group but also project tag, product owner tag.

I'm sure I'm just missing something...

**Comment by heikkipora** [comment]
Tags (in this context) do not refer to git tags but GitLab project tags (called 'Topics' in the GitLab UI nowadays).
I guess the name tag is misleading and should be changed in `gitlab-radiator`.

The name was originally chosen because the entities are called `tags` in the GitLab API,
